theme: jekyll-theme-cayman
title: ownCloud Installation Quickstart
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
output: 
  html_document:
    theme: journal
    highlight: espresso
    toc: true
    toc_depth: 4
    toc_float:
      collapsed: false
